########################## NumercialImage Configuration ###########################

#==========================  Pipeline configuration ============================

pipeline:
    - label: 'first step'  
      type: reduce
      pix_size: 21
      image_type: int_rgb
    - label: 'second step' 
      type: quantize
    - label: 'third step'  
      type: determine_lines_multi_color
    - label: 'fourth step' 
      type: convert_to_html
      multicolor: true

      
      